title: Schmitech
description: Custom AI Solutions
email: info@schmitech.ai
baseurl: ""
url: "https://www.schmitech.ai"

# Theme settings
theme: minima
minima:
  skin: dark
  social_links:
    - platform: github
      user_url: "https://github.com/schmitech"
    - platform: linkedin
      user_url: "https://linkedin.com/company/schmitech"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
header_pages:
  - about.md
  - solutions.md
  - use-cases.md
  - careers.md
  - contact.md

markdown: kramdown
timezone: America/Toronto

# Collections
collections:
  solutions:
    output: true
    permalink: /:collection/:name
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title

sass:
  sass_dir: _sass
  style: compressed