title: Schmitech
description: Custom AI Solutions
email: info@schmitech.ai
baseurl: ""
url: "https://www.schmitech.ai"

theme: minima
minima:
  skin: dark
  social_links:
    - platform: github
      user_url: "https://github.com/schmitech"
    - platform: linkedin
      user_url: "https://linkedin.com/company/schmitech"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md
  - use-cases.md
  - careers.md
  - contact.md

markdown: kramdown
timezone: America/Toronto

collections:
  use-cases:
    output: true
    permalink: /blog/:year/:month/:day/:title

sass:
  sass_dir: _sass
  style: compressed