title: Schmitech
description: Custom AI Solutions
email: info@schmitech.ai
baseurl: ""
url: "https://schmitech.ai"

# Theme settings
theme: minima
minima:
  skin: classic
  social_links:
    - platform: github
      user_url: "https://github.com/schmitech"
    - platform: linkedin
      user_url: "https://linkedin.com/company/schmitech"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
header_pages:
  - about.md
  - services.md
  - use-cases.md
  - models.md
  - contact.md

# Collections
collections:
  services:
    output: true
    permalink: /:collection/:name
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title